# Name	Description	Possible values	Default
# command_key	Key to open command line	Single character	:
# initial_screen	Screen to show after startup	"library", "search", "queue", "cover"1	"library"
# use_nerdfont	Turn nerdfont glyphs on/off	true, false	false
# flip_status_indicators	Reverse play/pause icon meaning	true, false	false
# backend	Audio backend to use	Run ncspot -h for a list of devices String 3	
# backend_device	Audio device to configure the backend	String	
# audio_cache	Enable caching of audio files	true, false	true
# audio_cache_size	Maximum size of audio cache in MiB	Number	
# volnorm	Enable volume normalization	true, false	false
# volnorm_pregain	Normalization pregain to apply (if enabled)	Number	0
# default_keybindings	Enable default keybindings	true, false	false
# notify	Enable desktop notifications	true, false	false
# bitrate	Audio bitrate to use for streaming	96, 160, 320	320
# album_column	Show album column for tracks	true, false	true
# gapless	Enable gapless playback	true, false	false
# shuffle	Set default shuffle state	true, false	false
# repeat	Set default repeat mode	off, track, playlist	off
# [theme]	Custom theme	See custom theme	
[theme]
# background = "black"
# primary = "light white"
# secondary = "light black"
# title = "green"
# playing = "green"
# playing_selected = "light green"
# playing_bg = "black"
# highlight = "light white"
# highlight_bg = "#484848"
# error = "light white"
# error_bg = "red"
# statusbar = "black"
# statusbar_progress = "green"
# statusbar_bg = "green"
# cmdline = "light white"
# cmdline_bg = "black"
# search_match = "light red"
[keybindings]
# "Shift+i" = "seek +10000"
